import Head from 'next/head'
import NBHead from '../components/head'
import Image from 'next/image'
import Lottie from "react-lottie";
import animMap from "/public/animations/anim_map.json";
import animMain from "/public/animations/anim_main.json";
import animGrowth from "/public/animations/anim_growth.json";

export default function About() {

    const mapLottieOptions = {
        loop: true,
        autoplay: true,
        animationData: animMap,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice",
        },
    };

    const mainLottieOptions = {
        loop: true,
        autoplay: true,
        animationData: animMain,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice",
        },
    };

    const growthLottieOptions = {
        loop: true,
        autoplay: true,
        animationData: animGrowth,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice",
        },
    };

    return <div>
        <Head>
            <title>ABout NonaByte Factory</title>
            <meta name="description" content="Generated by NonaByte Factory" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <NBHead />

        <main style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
            <div style={{ width: '100%', marginTop: '24px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Image src='/images/img_introduce.png' width={1920} height={392} />
            </div>

            <div style={{ maxWidth: '960px', marginTop: '90px' }}>
                <span style={{ color: '#FEFEFE', opacity: '0.6', fontSize: '20px' }}>
                    Company Profile
                </span>

                <div style={{ fontSize: '40px', fontWeight: 'bold', marginTop: '12px' }}>
                    公司介绍
                </div>

                <div style={{ fontSize: '20px', color: '#FEFEFE', lineHeight: '40px', marginTop: '24px' }}>
                    超级工厂总部坐标上海区块链技术创新与产业基地。我们的团队深耕区块链领域多年，致力于夯实底层基础 建设，推动生态应用落地，为各需求客户提供法律、风控、政策、技术等方面的权威指导与一手服务。未来， 超级工厂将在舟山、海南、新加坡、瑞士等多地设立办公室，为全球算力、全球IDC布局创建更健康的共识内大系统支持。
                </div>
            </div>

            {/* Map Animation */}
            <div style={{ marginTop: '160px' }}>
                <Lottie options={mapLottieOptions} isClickToPauseDisabled></Lottie>
            </div>

            {/*  Main Animation */}
            <div style={{ marginTop: '60px' }}>
                <Lottie options={mainLottieOptions} isClickToPauseDisabled></Lottie>
            </div>


            {/*  Growth Animation */}
            <div style={{ marginTop: '60px' }}>
                <Lottie options={growthLottieOptions} isClickToPauseDisabled></Lottie>
            </div>

            <div style={{}}>
                <Image src='/images/img_bg_map.png' width={1920} height={947}></Image>
            </div>

            {/* SINSO */}
            <div style={{ marginTop: '200px', backgroundColor: '#1A723E', width: '100%', height: '800px' }}>
                <span style={{ fontSize: '100px' }}>SINSO, Animation</span>
            </div>

        </main>


    </div >
}