import Head from 'next/head'
import NBHead from '../components/head'
import Image from 'next/image'
import Lottie from "react-lottie";
import animMap from "/public/animations/anim_map.json";
import animGrowth from "/public/animations/anim_growth.json";

import ReactFullpage from '@fullpage/react-fullpage';
import styles from '../styles/About.module.css'
import ReactPlayer from 'react-player';

let animMapStop = true;
let animGrowthStop = true;

let videoNB1Playing = false;
let videoNB2Playing = false;
let videoNB3Playing = false;
let videoNB4Playing = false;
let astronomicalPlaying = false;
let sinsoPlaying = false;
let ipgroupPlaying = false;
let banbikPlaying = false;

function animationShouldStop(targetIndex, leavingIndex, direction) {
    if (targetIndex == 0 || leavingIndex == targetIndex) {
        return false;
    }

    if ((leavingIndex + 1 == targetIndex && direction == 'down')
        || (leavingIndex - 1 == targetIndex && direction == 'up')) {
        return false;
    }

    return true;
}

function onLeave(origin, destination, direction) {
    const leavingIndex = origin.index;
    animMapStop = animationShouldStop(1, leavingIndex, direction);
    animGrowthStop = animationShouldStop(6, leavingIndex, direction);

    let reachingIndex = destination.index;
    if (reachingIndex == 2) {
        videoNB1Playing = true;
        playVideoWhenReachingSection('nb1VideoId');
    }
    if (reachingIndex == 3) {
        videoNB2Playing = true;
        playVideoWhenReachingSection('nb2VideoId');
    }
    if (reachingIndex == 4) {
        videoNB3Playing = true;
        playVideoWhenReachingSection('nb3VideoId');
    }
    if (reachingIndex == 5) {
        videoNB4Playing = true;
        playVideoWhenReachingSection('nb4VideoId');
    }
    if (reachingIndex == 7) {
        astronomicalPlaying = true;
        playVideoWhenReachingSection('astronomical');
    }

    if (reachingIndex == 9) {
        ipgroupPlaying = true;
        playVideoWhenReachingSection('ipgroup');
    }
    if (reachingIndex == 10) {
        banbikPlaying = true;
        playVideoWhenReachingSection('banbik');
    }

    console.log("Leaving section " + reachingIndex);
}

function playVideoWhenReachingSection(videoId) {
    const videoElement = document.getElementById(videoId).getElementsByTagName('video')[0];
    videoElement.setAttribute('data-autoplay', '')
    videoElement.play();
}

function afterLoad(origin, destination, direction) {
    const loadIndex = destination.index;

    if (loadIndex == 0) {
        const profileLogo = document.getElementById('profileLogo');
        profileLogo.style.opacity = 0.1;
        profileLogo.style.transform = 'scale(1)'
        appearWithAnimation('profileContent', 200, 'animate__fadeInUp')
    }

    if (loadIndex == 8) {
        sinsoPlaying = true;
        playVideoWhenReachingSection('sinso');
    }
}

function appearWithAnimation(elementId, delay, animationId) {
    const element = document.getElementById(elementId);

    setTimeout(() => {
        element.style.opacity = 1;
        element.classList.add('animate__animated');
        element.classList.add(animationId);
    }, delay);
}

export default function About() {

    const mapLottieOptions = {
        loop: true,
        autoplay: true,
        animationData: animMap,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice",
        },
    };

    const growthLottieOptions = {
        loop: false,
        autoplay: true,
        animationData: animGrowth,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice",
        },
    };

    return <div>
        <Head>
            <title>ABout NonaByte Factory</title>
            <meta name="description" content="Generated by NonaByte Factory" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <ReactFullpage
            scrollOverflow={true}
            sectionsColor={["#081508", "#081508", "#081508", "#081508", "#081508", "#081508", "#081508", "#081508"]}
            onLeave={onLeave.bind(this)}
            afterLoad={afterLoad.bind(this)}
            anchors={['CompanyProfile', 'NBMap', 'NBFactory', 'HardwareSupply', 'TechSupply', 'CapitalSupply', 'Growth', 'SINSO']}
            navigation={true}
            navigationTooltips={['CompanyProfile', 'NBMap', 'NBFactory', 'HardwareSupply', 'TechSupply', 'CapitalSupply', 'Growth', 'SINSO']}
            render={({ state, fullpageApi }) => {
                return (
                    <div id="fullpage-wrapper">
                        <div className="section section1">
                            <div style={{ height: '100%' }}>
                                <NBHead />

                                <div className={styles.center} >
                                    <div id='profileLogo' style={{ marginTop: '40px', width: '100vw', height: '20vh' }} className={styles.profileLogo} >
                                        <Image src='/images/img_introduction.svg' layout='fill' />
                                    </div>
                                </div>

                                <div style={{ height: '100%' }} className={styles.center}>
                                    <div id='profileContent' style={{ opacity: 0, maxWidth: '960px', margin: '10vh' }}>
                                        <span style={{ color: '#FEFEFE', opacity: '0.6', fontSize: '20px' }}>
                                            Company Profile
                                        </span>

                                        <div style={{ fontSize: '40px', fontWeight: 'bold', marginTop: '12px' }}>
                                            公司介绍
                                        </div>

                                        <div className={styles.profileContent} >
                                            超级工厂总部坐标上海区块链技术创新与产业基地。我们的团队深耕区块链领域多年，致力于夯实底层基础 建设，推动生态应用落地，为各需求客户提供法律、风控、政策、技术等方面的权威指导与一手服务。未来， 超级工厂将在舟山、海南、新加坡、瑞士等多地设立办公室，为全球算力、全球IDC布局创建更健康的共识内大系统支持。
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>


                        <div className="section">
                            <div>
                                <Lottie isStopped={animMapStop} options={mapLottieOptions} isClickToPauseDisabled></Lottie>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <div style={{ width: '100%' }}>
                                    <ReactPlayer id='nb1VideoId' config={{
                                        file: {
                                            attributes: {
                                                autoPlay: true,
                                                muted: true
                                            }
                                        }
                                    }} muted={true} width='100vw' height='100vh' url="videos/supply_1.mp4" playing={videoNB1Playing} style={{ pointerEvents: 'none' }} />
                                </div>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <div style={{ width: '100%' }}>
                                    <ReactPlayer id='nb2VideoId' config={{
                                        file: {
                                            attributes: {
                                                autoPlay: true,
                                                muted: true
                                            }
                                        }
                                    }} muted={true} width='100vw' height='100vh' url="videos/supply_2.mp4" playing={videoNB2Playing} style={{ pointerEvents: 'none' }} />
                                </div>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <div style={{ width: '100%' }}>
                                    <ReactPlayer id='nb3VideoId' config={{
                                        file: {
                                            attributes: {
                                                autoPlay: true,
                                                muted: true
                                            }
                                        }
                                    }} muted={true} width='100vw' height='100vh' url="videos/supply_3.mp4" playing={videoNB3Playing} style={{ pointerEvents: 'none' }} />
                                </div>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <div style={{ width: '100%' }}>
                                    <ReactPlayer id='nb4VideoId' config={{
                                        file: {
                                            attributes: {
                                                autoPlay: true,
                                                muted: true
                                            }
                                        }
                                    }} muted={true} width='100vw' height='100vh' url="videos/supply_4.mp4" playing={videoNB4Playing} style={{ pointerEvents: 'none' }} />
                                </div>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <Lottie height='100vh' width='100vw' isStopped={animGrowthStop} options={growthLottieOptions} isClickToPauseDisabled></Lottie>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <div style={{ width: '100%' }}>
                                    <ReactPlayer id='astronomical' config={{
                                        file: {
                                            attributes: {
                                                autoPlay: true,
                                                muted: true
                                            }
                                        }
                                    }} muted={true} width='100vw' height='100vh' url="videos/astronomical.mp4" playing={astronomicalPlaying} style={{ pointerEvents: 'none' }} />
                                </div>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <div style={{ width: '100%' }}>
                                    <ReactPlayer id='sinso' config={{
                                        file: {
                                            attributes: {
                                                autoPlay: true,
                                                muted: true
                                            }
                                        }
                                    }} muted={true} width='100vw' height='100vh' url="videos/sinso.mp4" playing={sinsoPlaying} style={{ pointerEvents: 'none' }} />
                                </div>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <div style={{ width: '100%' }}>
                                    <ReactPlayer id='ipgroup' config={{
                                        file: {
                                            attributes: {
                                                autoPlay: true,
                                                muted: true
                                            }
                                        }
                                    }} muted={true} width='100vw' height='100vh' url="videos/ipgroup.mp4" playing={ipgroupPlaying} style={{ pointerEvents: 'none' }} />
                                </div>
                            </div>
                        </div>

                        <div className="section">
                            <div className={styles.sectionContainer}>
                                <div style={{ width: '100%' }}>
                                    <ReactPlayer id='banbik' config={{
                                        file: {
                                            attributes: {
                                                autoPlay: true,
                                                muted: true
                                            }
                                        }
                                    }} muted={true} width='100vw' height='100vh' url="videos/banbik.mp4" playing={banbikPlaying} style={{ pointerEvents: 'none' }} />
                                </div>
                            </div>
                        </div>

                    </div>
                );
            }}
        />
    </div >
}