import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NBHead from '../components/head'
import ReactFullpage from '@fullpage/react-fullpage';
import ReactPlayer from 'react-player';

const startIndex = 4;
const stepPx = 360;
let videoBoxPlaying = false;

function onLeave(origin, destination, direction) {
  let reachingIndex = destination.index;
  let top = -1;
  let transition = 'all 1s ease-in';
  let highlightIndex = 0;
  let opacity = 0;
  if (reachingIndex >= startIndex) {
    const offset = reachingIndex - startIndex
    top = -offset * stepPx;
    transition = 'all 1s ease-out';
    highlightIndex = offset + 1;
    opacity = 1;

    fadeIn('cardPageTitle' + (offset + 1), 0, 'animate__fadeInUpBig');
    fadeIn('cardPageSubtitle' + (offset + 1), 100, 'animate__fadeInUpBig');
    fadeIn('cardPageContent' + + (offset + 1), 250, 'animate__fadeInUpBig');
  } else {
    top = -1;
    transition = 'all 500ms ease';
    opacity = 0;
  }

  const cardPanel1 = document.getElementById('cardPanel1');
  cardPanel1.style.transition = transition;
  cardPanel1.style.opacity = opacity;
  cardPanel1.style.marginTop = top == -1 ? '200%' : (parseInt(top * 1.5) - 1120) + 'px';

  const cardPanel2 = document.getElementById('cardPanel2');
  cardPanel2.style.transition = transition;
  cardPanel2.style.opacity = opacity;
  cardPanel2.style.marginTop = top == -1 ? '200%' : (parseInt(top * 2) - 720) + 'px';

  const cardPanel3 = document.getElementById('cardPanel3');
  cardPanel3.style.transition = transition;
  cardPanel3.style.opacity = opacity;
  cardPanel3.style.marginTop = top == -1 ? '200%' : (top - 120) + 'px';

  const highlightCards = cardPanel3.childNodes;
  for (const [idx, card] of highlightCards.entries()) {
    if (idx == highlightIndex) {
      card.style.filter = 'brightness(100%)';
    } else {
      card.style.filter = 'brightness(30%)';
    }
  }
}


function afterLoad(origin, destination, direction) {
  const loadIndex = destination.index;

  if (loadIndex == 0) {
    const videoElement = document.getElementById('homeVideoId').getElementsByTagName('video')[0];
    videoElement.setAttribute('data-autoplay', '')
    videoElement.play();
    fadeIn('logo', 0, 'animate__slideInLeft');
    fadeIn('slogan', 0, 'animate__slideInRight');
  }

  if (loadIndex == 1) {
    fadeIn('missionImg', 0, 'animate__fadeInLeft');
    fadeIn('missionTitle', 300, 'animate__fadeInDown');
    fadeIn('missionContent', 600, 'animate__fadeInUp');
  }

  if (loadIndex == 2) {
    fadeIn('linkageContent', 0, 'animate__fadeInDown');
    fadeIn('linkageImg', 200, 'animate__zoomInDown');
  }

  if (loadIndex == 3) {
    const videoElement = document.getElementById('boxVideoId').getElementsByTagName('video')[0];
    videoElement.setAttribute('data-autoplay', '')
    videoElement.play();
    videoBoxPlaying = true;
  }
}

function fadeIn(elementId, delay, animation) {
  const element = document.getElementById(elementId);

  setTimeout(() => {
    element.style.opacity = 1;
    element.classList.add('animate__animated');
    element.classList.add(animation);
  }, delay);
}

export default function Home() {

  return (
    <div>
      <Head>
        <title>NonaByte Factory</title>
        <meta name="description" content="Generated by NonaByte Factory" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id='cardContainer' style={{ display: 'flex', position: 'absolute', zIndex: 1 }}>
        <div id='cardPanel1' className={styles.cardPanel} style={{ marginLeft: '-5vw' }}>
          <div className={styles.card} >
            <Image src='/images/card1.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card2.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card3.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card4.png' width={240} height={330}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card5.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card6.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card7.png' width={240} height={730}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card1.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card2.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card3.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card4.png' width={240} height={330}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card5.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card6.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card7.png' width={240} height={730}></Image>
          </div>
        </div>

        <div id='cardPanel2' className={styles.cardPanel} style={{ marginLeft: '1.5vw' }}>
          <div className={styles.card} >
            <Image src='/images/card1.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card2.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card3.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card4.png' width={240} height={330}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card5.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card6.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card7.png' width={240} height={730}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card1.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card2.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card3.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card4.png' width={240} height={330}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card5.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card6.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card7.png' width={240} height={730}></Image>
          </div>
        </div>

        <div id='cardPanel3' className={styles.cardPanel} style={{ marginLeft: '1.5vw' }}>
          <div className={styles.card} >
            <Image src='/images/card1.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card2.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card3.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card4.png' width={240} height={330}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card5.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card6.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card7.png' width={240} height={730}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card1.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card2.png' width={240} height={358}></Image>
          </div>
          <div className={styles.card} >
            <Image src='/images/card3.png' width={240} height={358}></Image>
          </div>
        </div>

      </div>


      <ReactFullpage
        scrollOverflow={true}
        sectionsColor={["#051403", "#081508", "#081508", "#081508", "#132B11", "#0F260E", "#0C210B", "#091C08", "#081807", "#061505"]}
        onLeave={onLeave.bind(this)}
        afterLoad={afterLoad.bind(this)}
        anchors={['Home', 'Mission', 'SuperLinkage', 'TBD']}
        navigation={true}
        navigationTooltips={['Home', 'Mission', 'SuperLinkage', 'TBD']}
        render={({ state, fullpageApi }) => {
          return (
            <div id="fullpage-wrapper" >

              {/* NB 超级工厂 */}
              <div className="section section1">
                <div style={{ height: '100%' }}>
                  <NBHead>
                  </NBHead>
                  <div className={styles.sectionContainer}>

                    <div style={{ maxWidth: '1200px', marginTop: '60px', width: '80%' }} className={styles.titleContainer}>
                      <div id='logo' style={{ opacity: 0, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                        <div className={styles.logoContainer}>
                          <Image className={styles.logoImage} src='/images/logo_frame.png' width={320} height={88}></Image>
                          <div className={styles.logoText}>NB 超级工厂</div>
                        </div>

                        <span className={styles.logoSubtitle}>
                          NonaByte Factory
                        </span>
                      </div>


                      <div id='slogan' style={{ opacity: 0 }} className={styles.logoRightMenu} >
                        <p>
                          塑造｜ 应用｜ 赋权
                        </p>
                        <p>
                          区块链项目生态2.0
                        </p>
                      </div>
                    </div>
                    <div style={{ maxWidth: '1400px', marginTop: '40px' }}>
                      <ReactPlayer id='homeVideoId' config={{
                        file: {
                          attributes: {
                            autoPlay: true,
                            muted: true
                          }
                        }
                      }} muted={true} width='100%' height='70vh' url="videos/home.mp4" playing={true} style={{ pointerEvents: 'none' }} />
                    </div>

                  </div>

                </div>
              </div>


              {/*  NB Factory’s MISSION */}
              <div className="section">
                <div className={styles.sectionContainer}>

                  <div style={{ maxWidth: '1200px', width: '80%', display: 'flex', alignItems: 'center' }}>
                    <div id='missionImg' style={{ opacity: 0, width: '480px', height: '760px' }}>
                      <Image src='/images/img_mission.png' layout='fill' objectFit='scale-down' ></Image>
                    </div>

                    <div style={{ position: 'relative', marginLeft: 47 + 'px' }}>
                      <div id='missionTitle' style={{ opacity: 0, position: 'relative', display: 'flex', flexDirection: 'column', }} className={styles.missionTitle}>
                        <div>
                          <Image src='/images/img_text_frame.png' width={490} height={88}>
                          </Image>
                        </div>
                        <div className={styles.center} style={{ position: 'absolute', width: '490px', height: '88px' }}>
                          NB Factory&apos;s MISSION
                        </div>
                      </div>

                      <div id='missionContent' style={{ opacity: 0 }} >
                        <div style={{ textAlign: 'justify', textJustify: 'inter-word' }} className={styles.missionContent}>
                          价值数据宇宙，人类未来全新的疆域，这是属于星舰FilNB的航程。 超级工厂的任务是为生态成员提供更多有效算力，<br />
                          肯定.赋能.链接每一有效存储，加速世界向web3.0时代过渡。持续生产持续创造，奋力挣脱大地粗暴的束缚，坚勇航向前人所未至的文明，去触摸造物主温柔的脸庞，去实现生命体对美、对好奇心的想象。
                        </div>

                        <div style={{ opacity: 0, position: 'absolute', right: 0 }}>
                          <Image src='/images/ic_comma.png' width={69} height={48}></Image>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>


              {/* Super Linkage */}
              <div className="section">
                <div style={{ position: 'relative', height: '100%' }} className={styles.sectionContainer}>
                  <div id='linkageContent' style={{ opacity: 0, maxWidth: '1200px', width: '80%' }}>
                    <div style={{ padding: '2px 8px', backgroundColor: '#033915', width: 'fit-content' }}>
                      CHAO JI LIAN DONG
                    </div>

                    <div style={{ display: 'flex', marginTop: '50px' }}>
                      <span style={{ fontSize: '80px', fontWeight: 'bold' }}>
                        超级联动
                      </span>
                      <div style={{ marginLeft: '24px' }}>
                        <Image src='/images/ic_comma.png' width={46} height={32}></Image>
                      </div>
                    </div>

                    <div style={{ width: '80px', height: '8px', backgroundColor: '#2ECC4F', marginTop: '16px' }} />

                    <p style={{ marginTop: '80px', lineHeight: '40px', fontSize: '20px' }}>
                      超级工厂下设六大品牌，愿景以NB作为可实现的超强算力计数单位，孵化、支持顶尖的「帮助人类实现可持续化发展的数据」项目，<br /> 最终实现人类从现实世界到交互世界的「价值升级」工程。
                      <p>
                        利用强大的供应链网络、领先的资源融合速度与丰富投资组合经验，我们将为共创者提供更富远见的洞察力。
                      </p>
                    </p>
                  </div>

                  <div id='linkageImg' style={{ opacity: 0, position: 'absolute', bottom: '0', }}>
                    <Image src='/images/img_superlinkage.png' height={216} width={1920}></Image>
                  </div>
                </div>
              </div>

              {/* Box video */}
              <div className="section">
                <div className={styles.sectionContainer}>
                  <div style={{ width: '80%', padding: '120px' }}>
                    <ReactPlayer id='boxVideoId' config={{
                      file: {
                        attributes: {
                          autoPlay: true,
                          muted: true
                        }
                      }
                    }} muted={true} width='100%' height='auto' url="videos/box.mp4" playing={videoBoxPlaying} style={{ pointerEvents: 'none' }} />
                  </div>
                </div>
              </div>


              <div className="section">
                <div style={{ marginLeft: '28vw' }} className={styles.sectionContainer}>
                  <div>
                    <div id='cardPageTitle1' className={styles.cardPageTitle}>
                      供应链<span style={{ color: '#2ECC4F' }}>金融</span>
                    </div>

                    <div id='cardPageSubtitle1' className={styles.cardPageSubtitle}>
                      FilNB
                    </div>

                    <div id='cardPageContent1' className={styles.cardPageContent}>
                      超级工厂的核心引擎；提供场景. 技术. 资本. 用户. 算力. 数据等全维角度的多选项、深合作的超级供应网。对高价值资产、强稀缺资源在备货量级、速度、渠道层面均具有超级优势。
                    </div>
                  </div>
                </div>
              </div>


              <div className="section">
                <div style={{ marginLeft: '28vw' }} className={styles.sectionContainer}>
                  <div>
                    <div id='cardPageTitle2' className={styles.cardPageTitle}>
                      <span style={{ color: '#2ECC4F' }}>技术</span>服务商
                    </div>

                    <div id='cardPageSubtitle2' className={styles.cardPageSubtitle}>
                      FounCode
                    </div>

                    <div id='cardPageContent2' className={styles.cardPageContent}>
                      超级工厂的生产车间；除IPFS外，还高度关注于CHIA、SWARM、MASS、NFT、DFINITY等多生态项目。重点生产线在元器硬件.算法软件. 集群维护等方面均占据行业领先地位，可快速调度，提供全球云算力. 全球IDC支持。</div>
                  </div>
                </div>
              </div>

              <div className="section">
                <div style={{ marginLeft: '28vw' }} className={styles.sectionContainer}>
                  <div>
                    <div id='cardPageTitle3' className={styles.cardPageTitle}>
                      超级<span style={{ color: '#2ECC4F' }}>基金会</span>
                    </div>

                    <div id='cardPageSubtitle3' className={styles.cardPageSubtitle}>
                      eXmit
                    </div>

                    <div id='cardPageContent3' className={styles.cardPageContent}>
                      超级工厂的强大外援；对工厂目标意向生态或项目进行商业与科学 两大角度的背调、评估、投资与协作运营，为工厂系统内成员提供 各类服务与背书。合作全球头部基金会，为超级工厂的战略布局 持续推进。</div>
                  </div>
                </div>
              </div>

              <div className="section">
                <div style={{ marginLeft: '28vw' }} className={styles.sectionContainer}>
                  <div>
                    <div id='cardPageTitle4' className={styles.cardPageTitle}>
                      <span style={{ color: '#2ECC4F' }}>超级</span>实验室
                    </div>

                    <div id='cardPageSubtitle4' className={styles.cardPageSubtitle}>
                      LNBS
                    </div>

                    <div id='cardPageContent4' className={styles.cardPageContent}>
                      超级工厂的核级武器；对内，投入资金培养实验室专业科研队伍，
                      加速系统工具和服务的开发，提高工厂技术壁垒。对外，发现技术
                      基因占有优势的明星项目进行孵化和培育，实现成熟项目的立案
                      发币，升级工厂中坚力量。</div>
                  </div>
                </div>
              </div>

              <div className="section">
                <div style={{ marginLeft: '28vw' }} className={styles.sectionContainer}>
                  <div>
                    <div id='cardPageTitle5' className={styles.cardPageTitle}>
                      超级<span style={{ color: '#2ECC4F' }}>社区家</span>
                    </div>

                    <div id='cardPageSubtitle5' className={styles.cardPageSubtitle}>
                      NBer
                    </div>

                    <div id='cardPageContent5' className={styles.cardPageContent}>
                      超级工厂的团结工会；每一处脉络都有细节，每一处服务都有用心。品牌旨在为矿工端提供教育内容，为用户端提供推广平台，为合作
                      端提供情感联系。用内容与回报重塑系统成员未来共识基因。</div>
                  </div>
                </div>
              </div>

              <div className="section">
                <div style={{ marginLeft: '28vw' }} className={styles.sectionContainer}>
                  <div>
                    <div id='cardPageTitle6' className={styles.cardPageTitle}>
                      <span style={{ color: '#2ECC4F' }}>数字</span>IP版权
                    </div>

                    <div id='cardPageSubtitle6' className={styles.cardPageSubtitle}>
                      NBU
                    </div>

                    <div id='cardPageContent6' className={styles.cardPageContent}>
                      超级工厂的厂牌之光；所有NBU成员均可在NB universal内申领虚拟身份和形象，突破次元进行互动，打造属于自己的项目IP. 真人IP.
                      内容IP. 偶像IP。</div>
                  </div>
                </div>
              </div>

            </div>
          );
        }}
      />
    </div>
  )
}
