import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NBHead from '../components/head'
import Lottie from "react-lottie";
import animMain from "/public/animations/anim_home.json";
import ReactFullpage from '@fullpage/react-fullpage';
function onLeave(origin, destination, direction) {
  const leavingIndex = origin.index;
  let reachingIndex = 0;
  if (direction == 'down') {
    reachingIndex = leavingIndex + 1;
  } else {
    reachingIndex = leavingIndex - 1;
  }

  console.log("Leaving section " + origin.index + ',' + direction + ', ' + reachingIndex);
}

function afterLoad(origin, destination, direction) {
  const loadIndex = destination.index;

  if (loadIndex == 0) {
  }

  if (loadIndex == 1) {
    fadeIn('missionImg', 0, 'animate__fadeInLeft');
    fadeIn('missionTitle', 300, 'animate__fadeInDown');
    fadeIn('missionContent', 600, 'animate__fadeInUp');
  }

  if (loadIndex == 2) {
    fadeIn('linkageContent', 0, 'animate__fadeInDown');
    fadeIn('linkageImg', 200, 'animate__zoomInDown');
  }

  if (loadIndex == 3) {
  }
}

function fadeIn(elementId, delay, animation) {
  const element = document.getElementById(elementId);

  setTimeout(() => {
    element.style.opacity = 1;
    element.classList.add('animate__animated');
    element.classList.add(animation);
  }, delay);
}

export default function Home() {

  const lottieOptions = {
    loop: true,
    autoplay: true,
    animationData: animMain,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };


  return (
    <div>
      <Head>
        <title>NonaByte Factory</title>
        <meta name="description" content="Generated by NonaByte Factory" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactFullpage
        scrollOverflow={true}
        sectionsColor={["#081508", "#081508", "#081508", "#081508"]}
        onLeave={onLeave.bind(this)}
        afterLoad={afterLoad.bind(this)}
        render={({ state, fullpageApi }) => {
          return (
            <div id="fullpage-wrapper">

              {/* NB 超级工厂 */}
              <div className="section section1">
                <div style={{ height: '100%' }}>
                  <NBHead>
                  </NBHead>
                  <div className={styles.sectionContainer}>

                    <div style={{ maxWidth: '1200px', marginTop: '108px' }} className={styles.titleContainer}>
                      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                        <div className={styles.logoContainer}>
                          <Image className={styles.logoImage} src='/images/logo_frame.png' width={320} height={88}></Image>
                          <div className={styles.logoText}>NB 超级工厂</div>
                        </div>

                        <span className={styles.logoSubtitle}>
                          NonaByte Factory
                        </span>
                      </div>


                      <div className={styles.logoRightMenu} >
                        <p>
                          塑造｜ 应用｜ 赋权
                        </p>
                        <p>
                          区块链项目生态2.0
                        </p>
                      </div>
                    </div>

                    <div className={styles.homeAnimation}>
                      <Lottie options={lottieOptions} isClickToPauseDisabled ></Lottie>
                    </div>
                  </div>

                </div>
              </div>


              {/*  NB Factory’s MISSION */}
              <div className="section">
                <div className={styles.sectionContainer}>

                  <div style={{ display: 'flex', alignItems: 'center' }}>
                    <div id='missionImg' style={{ opacity: 0, width: 563 + 'px', height: 850 + 'px' }}>
                      <Image src='/images/img_mission.png' width={563} height={850}></Image>
                    </div>

                    <div style={{ position: 'relative', marginLeft: 47 + 'px' }}>
                      <div id='missionTitle' style={{ opacity: 0, position: 'relative', display: 'flex', flexDirection: 'column', }} className={styles.missionTitle}>
                        <div>
                          <Image src='/images/img_text_frame.png' width={490} height={88}>
                          </Image>
                        </div>
                        <div className={styles.center} style={{ position: 'absolute', width: '490px', height: '88px' }}>
                          NB Factory&apos;s MISSION
                        </div>
                      </div>

                      <div id='missionContent' style={{ opacity: 0 }} >
                        <div style={{}} className={styles.missionContent}>
                          价值数据宇宙，人类未来全新的疆域，这是属于星舰FilNB的航程。超级工厂的任务是为生态成员提供更多有效算力，
                          肯定.赋能.链接每一有效存储，加速世界向web3.0时代过渡。持续生产持续创造，奋力挣脱大地粗暴的束缚，坚勇航向前人所未至的文明，去触摸造物主温柔的脸庞，去实现生命体对美、对好奇心的想象。
                        </div>

                        <div style={{ opacity: 0, position: 'absolute', right: 0 }}>
                          <Image src='/images/ic_comma.png' width={69} height={48}></Image>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>


              {/* Super Linkage */}
              <div className="section">
                <div style={{ position: 'relative', height: '100%' }} className={styles.sectionContainer}>
                  <div id='linkageContent' style={{ opacity: 0, maxWidth: '1200px', }}>
                    <div style={{ padding: '2px 8px', backgroundColor: '#033915', width: 'fit-content' }}>
                      CHAO JI LIAN DONG
                    </div>

                    <div style={{ display: 'flex', marginTop: '50px' }}>
                      <span style={{ fontSize: '80px', fontWeight: 'bold' }}>
                        超级联动
                      </span>
                      <div style={{ marginLeft: '24px' }}>
                        <Image src='/images/ic_comma.png' width={46} height={32}></Image>
                      </div>
                    </div>

                    <div style={{ width: '80px', height: '8px', backgroundColor: '#2ECC4F', marginTop: '16px' }} />

                    <p style={{ marginTop: '80px', lineHeight: '40px', fontSize: '20px' }}>
                      超级工厂下设六大品牌，愿景以NB作为可实现的超强算力计数单位，孵化、支持顶尖的「帮助人类实现可持续化发展的数据」项目， 最终实现人类从现实世界到交互世界的「价值升级」工程。
                      <p>
                        利用强大的供应链网络、领先的资源融合速度与丰富投资组合经验，我们将为共创者提供更富远见的洞察力。
                      </p>
                    </p>
                  </div>

                  <div id='linkageImg' style={{ opacity: 0, position: 'absolute', bottom: '0', }}>
                    <Image src='/images/img_superlinkage.png' height={216} width={1920}></Image>
                  </div>
                </div>
              </div>


              <div className="section">
                <div className={styles.sectionContainer}>
                  <div style={{ marginTop: '200px', backgroundColor: '#132B11', width: '100%', height: '800px' }}>
                    <span style={{ fontSize: '100px' }}>TBD, animation</span>
                  </div>

                </div>
              </div>

            </div>
          );
        }}
      />

      <div className={styles.container}>
        <Head>
          <title>NonaByte Factory</title>
          <meta name="description" content="Generated by NonaByte Factory" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NBHead>
        </NBHead>


        <main className={styles.main}>

          <div style={{ display: 'flex', flexDirection: 'column', maxWidth: '1080px', width: '80%' }}>
            {/* Title container */}
            <div className={styles.titleContainer}>

              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                <div className={styles.logoContainer}>
                  <Image className={styles.logoImage} src='/images/logo_frame.png' width={320} height={88}></Image>
                  <span className={styles.logoText}>NB 超级工厂</span>
                </div>

                <span style={{ color: '#FEFEFE', opacity: '0.6', marginTop: '8px', fontSize: '20px', }}>
                  NonaByte Factory
                </span>
              </div>


              <div style={{ color: '#FEFEFE', fontSize: '20px' }}>
                <p>
                  塑造｜ 应用｜ 赋权
                </p>
                <p>
                  区块链项目生态2.0
                </p>
              </div>
            </div>

            {/* Home Animation */}
            <div className={styles.homeAnimation}>
              <Lottie options={lottieOptions} isClickToPauseDisabled ></Lottie>
            </div>

            {/* Misson */}


            {/* Chaoji liandong */}


          </div>

          {/* Super Linkage */}
          <div style={{ marginTop: '169px', width: '100%' }}>
            <Image src='/images/img_superlinkage.png' height={216} width={1920}></Image>
          </div>

          {/* TBD */}
          <div style={{ marginTop: '200px', backgroundColor: '#132B11', width: '100%', height: '800px' }}>
            <span style={{ fontSize: '100px' }}>TBD, animation</span>
          </div>

        </main>




        <footer className={styles.footer}>
          <a
            href="https://baidu.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by NBFactory{' '}
            <span style={{ marginLeft: '16px' }} className={styles.logo}>
              <Image src="/images/logo.png" alt="NBFactory Logo" width={72} height={24} />
            </span>
          </a>
        </footer>
      </div>
    </div>

  )
}
