
import Head from 'next/head'
import NBHead from '../components/head'
import Image from 'next/image'

export default function Product() {

    return <div style={{ backgroundColor: '#081508' }}>
        <Head>
            <title>Product</title>
            <meta name="description" content="Generated by NonaByte Factory" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <NBHead />

        <main style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', width: '100%' }}>
            <div>
                {/* Product 1 */}
                <div style={{ marginTop: '108px', color: '#061505', backgroundColor: '#033915', padding: '2px 26px 2px 8px', fontSize: '20px', letterSpacing: '2px', lineHeight: '28px', width: 'fit-content' }}>
                    FiNB JI QUN JIA GOU TI GONG YOU ZUI XIN YI DAI Filecoin FEN BU SHI CUN CHU CHAN PIN
                </div>

                <div style={{ marginTop: '18px', display: 'flex', fontSize: '44px', color: 'white' }}>
                    FilNB 集群架构提供有最新⼀代Filecoin分布式存储产品
                    <div style={{ marginLeft: '8px' }}>
                        <Image src='/images/ic_comma.png' width={46} height={32}></Image>
                    </div>
                </div>

                <div style={{ width: '80px', height: '8px', backgroundColor: '#2ECC4F', marginTop: '28px' }} />

                <div style={{ marginTop: '40px' }}>
                    <Image src='/images/img_product_1.png' width={1080} height={460} />
                </div>


                {/* Product 2 */}
                <div style={{ marginTop: '280px', color: '#061505', backgroundColor: '#033915', padding: '2px 26px 2px 8px', fontSize: '20px', letterSpacing: '2px', lineHeight: '28px', width: 'fit-content' }}>
                    FiNB JI QUN JIA GOU TI GONG YOU ZUI XIN YI DAI Chia FEN BU SHI CUN CHU CHAN PIN
                </div>

                <div style={{ marginTop: '18px', display: 'flex', fontSize: '44px', color: 'white' }}>
                    FilNB 集群架构提供有最新⼀代Chia分布式存储产品
                    <div style={{ marginLeft: '8px' }}>
                        <Image src='/images/ic_comma.png' width={46} height={32}></Image>
                    </div>
                </div>

                <div style={{ width: '80px', height: '8px', backgroundColor: '#2ECC4F', marginTop: '28px' }} />

                <div style={{ marginTop: '40px' }}>
                    <Image src='/images/img_product_2.png' width={1080} height={450} />
                </div>


                {/* Product 3 */}
                <div style={{ marginTop: '280px', color: '#061505', backgroundColor: '#033915', padding: '2px 26px 2px 8px', fontSize: '20px', letterSpacing: '2px', lineHeight: '28px', width: 'fit-content' }}>
                    FiNB JI QUN JIA GOU TI GONG YOU ZUI XIN YI DAI Swarm FEN BU SHI CUN CHU CHAN PIN
                </div>

                <div style={{ marginTop: '18px', display: 'flex', fontSize: '44px', color: 'white' }}>
                    FilNB 集群架构提供有最新⼀代Swarm分布式存储产品
                    <div style={{ marginLeft: '8px' }}>
                        <Image src='/images/ic_comma.png' width={46} height={32}></Image>
                    </div>
                </div>

                <div style={{ width: '80px', height: '8px', backgroundColor: '#2ECC4F', marginTop: '28px' }} />

                <div style={{ marginTop: '40px' }}>
                    <Image src='/images/img_product_3.png' width={1080} height={600} />
                </div>
            </div>

            <div style={{ width: '240px', borderRadius: '10px', height: '64px', backgroundColor: '#2ECC4F', marginTop: '150px' }}></div>
            <div style={{ width: '220px', borderRadius: '10px', height: '64px', backgroundColor: '#2ECC4F', marginTop: '16px' }}></div>
            <div style={{ width: '200px', borderRadius: '10px', height: '64px', backgroundColor: '#2ECC4F', marginTop: '16px' }}></div>

            <div style={{ marginTop: '110px', fontSize: '56px', fontWeight: 'bold', lineHeight: '78px' }}>
                进行证明速度更快<br />
                完成分装时间更短
            </div>

            <div style={{ marginTop: '168px', fontSize: '32px', fontWeight: 'bold', lineHeight: '45px' }}>
                官方10倍有效算力加持
            </div>

            <div style={{ color: '#FEFEFE', marginTop: '16px', fontSize: '20px', lineHeight: '28px' }}>
                百P规模存储集群，高稳定大吞吐，支持无缝扩容
                <br />
                底层算法经过多轮优化改进，实测效能全网领先
            </div>

            <div style={{ marginTop: '92px', height: '957px', width: '1920px', backgroundColor: '#1A723E' }}>
            </div>

            <div style={{ position: 'relative' }}>
                <Image src='/images/img_bg_contact.png' width={1920} height={947} />
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', color: '#0AFF3D', position: 'absolute', left: '50%', top: '50%', fontWeight: 'bold', fontSize: '100px', transform: 'translate(-50%, -50%)' }}>
                    Contact US
                    <div style={{ fontSize: '32px', marginTop: '24px' }}>
                        上海市杨浦区湾谷科技园C6座701室
                    </div>

                    <div style={{ marginTop: '100px', display: 'flex', alignItems: 'center' }}>
                        <div style={{ marginLeft: '24px' }}>
                            <Image src='/images/img_qrcode_1.png' width={100} height={100} />
                        </div>

                        <div style={{ marginLeft: '24px' }}>
                            <Image src='/images/img_qrcode_2.png' width={100} height={100} />
                        </div>

                    </div>

                </div>

            </div>

        </main>

    </div>
}